[versions]
kotlin = "2.1.21"
gson = "2.13.1"
okhttp3 = "4.12.0"
coroutines = "1.10.2"
serialization = "1.8.1"
protobuf-plugin = "0.9.5"
protobuf-javalite = "4.31.1"
kotlin-logging = "7.0.7"

[libraries]
jetbrains-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-protobuf = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-javalite" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlinx-serialization  = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-protobuf  = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
